services:
  - type: web
    name: gitlab-bot
    runtime: python
    pythonVersion: 3.11.0  # Изменено с 3.11.8 на заведомо рабочую версию
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: GITLAB_TOKEN
        sync: false
      - key: GITLAB_URL
        value: https://gitlab.informatics.ru
      - key: PROJECT_ID
        sync: false